### ISSUE TITLE
desktop screen v00

### ISSUE THREAD

**Issue by otmanezahhari** [otmanezahhari/project03#1]
![comuter-tablett-screen-description](https://user-images.githubusercontent.com/44098229/100809460-7625d000-3436-11eb-98c8-0f39b7ff6541.jpg)
![comuter-tablett-screen-category](https://user-images.githubusercontent.com/44098229/100809462-76be6680-3436-11eb-8c56-3446de816116.jpg)
![comuter-tablett-screen-acceuil](https://user-images.githubusercontent.com/44098229/100809464-77ef9380-3436-11eb-84eb-8dbfcaf6cd64.jpg)

**Comment by Herondil** [comment]
Ok, si je comprends bien on a : 

1) En haut une page article ?

2) Au milieu une catégorie ?

3) En bas la page d'accueil ?

**Comment by otmanezahhari** [comment]
oui

**Comment by Herondil** [comment]
Ok, voici mes différentes questions : 

1) Les couleurs sont-elles celles que tu imagines sur le site ?
2) Je ne comprends pas ce qu'on va trouver dans le cadre à droite "News Category".
3) Sur la page d’accueil, on voit les deux catégories en même temps ? Avec juste 1 article pour la première et 2 pour la seconde ?
4) Je me demande aussi quels sont les "link" que tu écris sur les images. Est-ce qu'il s'agit d'autres catégories ou encore autre chose ?
5) Pourquoi ne pas avoir aligné les cadres des articles sur "category" ?
