### ISSUE TITLE
Mobile-screen V00

### ISSUE THREAD

**Issue by otmanezahhari** [otmanezahhari/project03#2]
![mobile-screen-acceuil](https://user-images.githubusercontent.com/44098229/100809503-90f84480-3436-11eb-9dac-82f4470deb4f.jpg)
![mobile-screen-category](https://user-images.githubusercontent.com/44098229/100809511-92297180-3436-11eb-8467-9833b383411c.jpg)

**Comment by Herondil** [comment]
Est-ce qu'il s'agit de la page d'accueil en haut et catégorie en bas ?

**Comment by otmanezahhari** [comment]
oui

**Comment by Herondil** [comment]
Je ne comprends pas où seraient les bords de l'écran, est-ce que tu peux les indiquer ?
